export enum FactionName {
    Illuminati = "Illuminati",
    Daedalus = "Daedalus",
    TheCovenant = "The Covenant",
    ECorp = "ECorp",
    MegaCorp = "MegaCorp",
    BachmanAssociates = "Bachman & Associates",
    BladeIndustries = "Blade Industries",
    NWO = "NWO",
    ClarkeIncorporated = "Clarke Incorporated",
    OmniTekIncorporated = "OmniTek Incorporated",
    FourSigma = "Four Sigma",
    KuaiGongInternational = "KuaiGong International",
    FulcrumSecretTechnologies = "Fulcrum Secret Technologies",
    BitRunners = "BitRunners",
    TheBlackHand = "The Black Hand",
    NiteSec = "NiteSec",
    Aevum = "Aevum",
    Chongqing = "Chongqing",
    Ishima = "Ishima",
    NewTokyo = "New Tokyo",
    Sector12 = "Sector-12",
    Volhaven = "Volhaven",
    SpeakersForTheDead = "Speakers for the Dead",
    TheDarkArmy = "The Dark Army",
    TheSyndicate = "The Syndicate",
    Silhouette = "Silhouette",
    Tetrads = "Tetrads",
    SlumSnakes = "Slum Snakes",
    Netburners = "Netburners",
    TianDiHui = "Tian Di Hui",
    CyberSec = "CyberSec",
    Bladeburners = "Bladeburners",
    ChurchOfTheMachineGod = "Church of the Machine God",
    ShadowsOfAnarchy = "Shadows of Anarchy",
}

export enum Colors {
    black = "\u001b[30m",
    red = "\u001b[31m",
    green = "\u001b[32m",
    yellow = "\u001b[33m",
    blue = "\u001b[34m",
    magenta = "\u001b[35m",
    cyan = "\u001b[36m",
    white = "\u001b[37m",
    brightBlack = "\u001b[30;1m",
    brightRed = "\u001b[31;1m",
    brightGreen = "\u001b[32;1m",
    brightYellow = "\u001b[33;1m",
    brightBlue = "\u001b[34;1m",
    brightMagenta = "\u001b[35;1m",
    brightCyan = "\u001b[36;1m",
    brightWhite = "\u001b[37;1m",
    reset = "\u001b[0m"
};

